apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trino-catalog-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage
  
